---
abstract: 'Fast XML-RPC parser with libxml'
author:
  - 'Tokuhiro Matsuno <tokuhirom AAJKLFJEF GMAIL COM>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RPC-XML-Parser-LibXML
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  Encode: 0
  MIME::Base64: 0
  RPC::XML: 0.73
  XML::LibXML: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tokuhirom/p5-RPC-XML-Parser-LibXML.git
version: 0.05
